package third.world.hao.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table chat
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Chat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.role
     *
     * @mbg.generated
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.char_time
     *
     * @mbg.generated
     */
    private Date charTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.id
     *
     * @return the value of chat.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.id
     *
     * @param id the value for chat.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.user_id
     *
     * @return the value of chat.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.user_id
     *
     * @param userId the value for chat.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.role
     *
     * @return the value of chat.role
     *
     * @mbg.generated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.role
     *
     * @param role the value for chat.role
     *
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.char_time
     *
     * @return the value of chat.char_time
     *
     * @mbg.generated
     */
    public Date getCharTime() {
        return charTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.char_time
     *
     * @param charTime the value for chat.char_time
     *
     * @mbg.generated
     */
    public void setCharTime(Date charTime) {
        this.charTime = charTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.content
     *
     * @return the value of chat.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.content
     *
     * @param content the value for chat.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}