package third.world.hao.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table revenue
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Revenue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.parent
     *
     * @mbg.generated
     */
    private String parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.month
     *
     * @mbg.generated
     */
    private Integer month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.before_salary
     *
     * @mbg.generated
     */
    private BigDecimal beforeSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.sum_salary
     *
     * @mbg.generated
     */
    private BigDecimal sumSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.five_money
     *
     * @mbg.generated
     */
    private BigDecimal fiveMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.sum_five
     *
     * @mbg.generated
     */
    private BigDecimal sumFive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.zhuan_money
     *
     * @mbg.generated
     */
    private BigDecimal zhuanMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.sum_zhuan
     *
     * @mbg.generated
     */
    private BigDecimal sumZhuan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.base_reduce
     *
     * @mbg.generated
     */
    private BigDecimal baseReduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.sum_base
     *
     * @mbg.generated
     */
    private BigDecimal sumBase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.ying_salary
     *
     * @mbg.generated
     */
    private BigDecimal yingSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.shui_percent
     *
     * @mbg.generated
     */
    private BigDecimal shuiPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.su_kou
     *
     * @mbg.generated
     */
    private BigDecimal suKou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.lei_ying
     *
     * @mbg.generated
     */
    private BigDecimal leiYing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.lei_jiao
     *
     * @mbg.generated
     */
    private BigDecimal leiJiao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.dang
     *
     * @mbg.generated
     */
    private BigDecimal dang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table revenue
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.id
     *
     * @return the value of revenue.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.id
     *
     * @param id the value for revenue.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.parent
     *
     * @return the value of revenue.parent
     *
     * @mbg.generated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.parent
     *
     * @param parent the value for revenue.parent
     *
     * @mbg.generated
     */
    public void setParent(String parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.user_id
     *
     * @return the value of revenue.user_id
     *
     * @mbg.generated
     */


    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.month
     *
     * @return the value of revenue.month
     *
     * @mbg.generated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.month
     *
     * @param month the value for revenue.month
     *
     * @mbg.generated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.before_salary
     *
     * @return the value of revenue.before_salary
     *
     * @mbg.generated
     */
    public BigDecimal getBeforeSalary() {
        return beforeSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.before_salary
     *
     * @param beforeSalary the value for revenue.before_salary
     *
     * @mbg.generated
     */
    public void setBeforeSalary(BigDecimal beforeSalary) {
        this.beforeSalary = beforeSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.sum_salary
     *
     * @return the value of revenue.sum_salary
     *
     * @mbg.generated
     */
    public BigDecimal getSumSalary() {
        return sumSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.sum_salary
     *
     * @param sumSalary the value for revenue.sum_salary
     *
     * @mbg.generated
     */
    public void setSumSalary(BigDecimal sumSalary) {
        this.sumSalary = sumSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.five_money
     *
     * @return the value of revenue.five_money
     *
     * @mbg.generated
     */
    public BigDecimal getFiveMoney() {
        return fiveMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.five_money
     *
     * @param fiveMoney the value for revenue.five_money
     *
     * @mbg.generated
     */
    public void setFiveMoney(BigDecimal fiveMoney) {
        this.fiveMoney = fiveMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.sum_five
     *
     * @return the value of revenue.sum_five
     *
     * @mbg.generated
     */
    public BigDecimal getSumFive() {
        return sumFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.sum_five
     *
     * @param sumFive the value for revenue.sum_five
     *
     * @mbg.generated
     */
    public void setSumFive(BigDecimal sumFive) {
        this.sumFive = sumFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.zhuan_money
     *
     * @return the value of revenue.zhuan_money
     *
     * @mbg.generated
     */
    public BigDecimal getZhuanMoney() {
        return zhuanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.zhuan_money
     *
     * @param zhuanMoney the value for revenue.zhuan_money
     *
     * @mbg.generated
     */
    public void setZhuanMoney(BigDecimal zhuanMoney) {
        this.zhuanMoney = zhuanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.sum_zhuan
     *
     * @return the value of revenue.sum_zhuan
     *
     * @mbg.generated
     */
    public BigDecimal getSumZhuan() {
        return sumZhuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.sum_zhuan
     *
     * @param sumZhuan the value for revenue.sum_zhuan
     *
     * @mbg.generated
     */
    public void setSumZhuan(BigDecimal sumZhuan) {
        this.sumZhuan = sumZhuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.base_reduce
     *
     * @return the value of revenue.base_reduce
     *
     * @mbg.generated
     */
    public BigDecimal getBaseReduce() {
        return baseReduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.base_reduce
     *
     * @param baseReduce the value for revenue.base_reduce
     *
     * @mbg.generated
     */
    public void setBaseReduce(BigDecimal baseReduce) {
        this.baseReduce = baseReduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.sum_base
     *
     * @return the value of revenue.sum_base
     *
     * @mbg.generated
     */
    public BigDecimal getSumBase() {
        return sumBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.sum_base
     *
     * @param sumBase the value for revenue.sum_base
     *
     * @mbg.generated
     */
    public void setSumBase(BigDecimal sumBase) {
        this.sumBase = sumBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.ying_salary
     *
     * @return the value of revenue.ying_salary
     *
     * @mbg.generated
     */
    public BigDecimal getYingSalary() {
        return yingSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.ying_salary
     *
     * @param yingSalary the value for revenue.ying_salary
     *
     * @mbg.generated
     */
    public void setYingSalary(BigDecimal yingSalary) {
        this.yingSalary = yingSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.shui_percent
     *
     * @return the value of revenue.shui_percent
     *
     * @mbg.generated
     */
    public BigDecimal getShuiPercent() {
        return shuiPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.shui_percent
     *
     * @param shuiPercent the value for revenue.shui_percent
     *
     * @mbg.generated
     */
    public void setShuiPercent(BigDecimal shuiPercent) {
        this.shuiPercent = shuiPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.su_kou
     *
     * @return the value of revenue.su_kou
     *
     * @mbg.generated
     */
    public BigDecimal getSuKou() {
        return suKou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.su_kou
     *
     * @param suKou the value for revenue.su_kou
     *
     * @mbg.generated
     */
    public void setSuKou(BigDecimal suKou) {
        this.suKou = suKou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.lei_ying
     *
     * @return the value of revenue.lei_ying
     *
     * @mbg.generated
     */
    public BigDecimal getLeiYing() {
        return leiYing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.lei_ying
     *
     * @param leiYing the value for revenue.lei_ying
     *
     * @mbg.generated
     */
    public void setLeiYing(BigDecimal leiYing) {
        this.leiYing = leiYing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.lei_jiao
     *
     * @return the value of revenue.lei_jiao
     *
     * @mbg.generated
     */
    public BigDecimal getLeiJiao() {
        return leiJiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.lei_jiao
     *
     * @param leiJiao the value for revenue.lei_jiao
     *
     * @mbg.generated
     */
    public void setLeiJiao(BigDecimal leiJiao) {
        this.leiJiao = leiJiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.dang
     *
     * @return the value of revenue.dang
     *
     * @mbg.generated
     */
    public BigDecimal getDang() {
        return dang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.dang
     *
     * @param dang the value for revenue.dang
     *
     * @mbg.generated
     */
    public void setDang(BigDecimal dang) {
        this.dang = dang;
    }
}