package third.world.hao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RevenueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table revenue
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table revenue
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table revenue
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public RevenueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table revenue
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIsNull() {
            addCriterion("parent is null");
            return (Criteria) this;
        }

        public Criteria andParentIsNotNull() {
            addCriterion("parent is not null");
            return (Criteria) this;
        }

        public Criteria andParentEqualTo(String value) {
            addCriterion("parent =", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotEqualTo(String value) {
            addCriterion("parent <>", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThan(String value) {
            addCriterion("parent >", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThanOrEqualTo(String value) {
            addCriterion("parent >=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThan(String value) {
            addCriterion("parent <", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThanOrEqualTo(String value) {
            addCriterion("parent <=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLike(String value) {
            addCriterion("parent like", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotLike(String value) {
            addCriterion("parent not like", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentIn(List<String> values) {
            addCriterion("parent in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotIn(List<String> values) {
            addCriterion("parent not in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentBetween(String value1, String value2) {
            addCriterion("parent between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotBetween(String value1, String value2) {
            addCriterion("parent not between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(Integer value) {
            addCriterion("month =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(Integer value) {
            addCriterion("month <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(Integer value) {
            addCriterion("month >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("month >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(Integer value) {
            addCriterion("month <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(Integer value) {
            addCriterion("month <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<Integer> values) {
            addCriterion("month in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<Integer> values) {
            addCriterion("month not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(Integer value1, Integer value2) {
            addCriterion("month between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("month not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryIsNull() {
            addCriterion("before_salary is null");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryIsNotNull() {
            addCriterion("before_salary is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryEqualTo(BigDecimal value) {
            addCriterion("before_salary =", value, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryNotEqualTo(BigDecimal value) {
            addCriterion("before_salary <>", value, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryGreaterThan(BigDecimal value) {
            addCriterion("before_salary >", value, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("before_salary >=", value, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryLessThan(BigDecimal value) {
            addCriterion("before_salary <", value, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("before_salary <=", value, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryIn(List<BigDecimal> values) {
            addCriterion("before_salary in", values, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryNotIn(List<BigDecimal> values) {
            addCriterion("before_salary not in", values, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("before_salary between", value1, value2, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andBeforeSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("before_salary not between", value1, value2, "beforeSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryIsNull() {
            addCriterion("sum_salary is null");
            return (Criteria) this;
        }

        public Criteria andSumSalaryIsNotNull() {
            addCriterion("sum_salary is not null");
            return (Criteria) this;
        }

        public Criteria andSumSalaryEqualTo(BigDecimal value) {
            addCriterion("sum_salary =", value, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryNotEqualTo(BigDecimal value) {
            addCriterion("sum_salary <>", value, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryGreaterThan(BigDecimal value) {
            addCriterion("sum_salary >", value, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_salary >=", value, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryLessThan(BigDecimal value) {
            addCriterion("sum_salary <", value, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_salary <=", value, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryIn(List<BigDecimal> values) {
            addCriterion("sum_salary in", values, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryNotIn(List<BigDecimal> values) {
            addCriterion("sum_salary not in", values, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_salary between", value1, value2, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andSumSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_salary not between", value1, value2, "sumSalary");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyIsNull() {
            addCriterion("five_money is null");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyIsNotNull() {
            addCriterion("five_money is not null");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyEqualTo(BigDecimal value) {
            addCriterion("five_money =", value, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyNotEqualTo(BigDecimal value) {
            addCriterion("five_money <>", value, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyGreaterThan(BigDecimal value) {
            addCriterion("five_money >", value, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("five_money >=", value, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyLessThan(BigDecimal value) {
            addCriterion("five_money <", value, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("five_money <=", value, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyIn(List<BigDecimal> values) {
            addCriterion("five_money in", values, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyNotIn(List<BigDecimal> values) {
            addCriterion("five_money not in", values, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("five_money between", value1, value2, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andFiveMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("five_money not between", value1, value2, "fiveMoney");
            return (Criteria) this;
        }

        public Criteria andSumFiveIsNull() {
            addCriterion("sum_five is null");
            return (Criteria) this;
        }

        public Criteria andSumFiveIsNotNull() {
            addCriterion("sum_five is not null");
            return (Criteria) this;
        }

        public Criteria andSumFiveEqualTo(BigDecimal value) {
            addCriterion("sum_five =", value, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveNotEqualTo(BigDecimal value) {
            addCriterion("sum_five <>", value, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveGreaterThan(BigDecimal value) {
            addCriterion("sum_five >", value, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_five >=", value, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveLessThan(BigDecimal value) {
            addCriterion("sum_five <", value, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_five <=", value, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveIn(List<BigDecimal> values) {
            addCriterion("sum_five in", values, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveNotIn(List<BigDecimal> values) {
            addCriterion("sum_five not in", values, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_five between", value1, value2, "sumFive");
            return (Criteria) this;
        }

        public Criteria andSumFiveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_five not between", value1, value2, "sumFive");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyIsNull() {
            addCriterion("zhuan_money is null");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyIsNotNull() {
            addCriterion("zhuan_money is not null");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyEqualTo(BigDecimal value) {
            addCriterion("zhuan_money =", value, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyNotEqualTo(BigDecimal value) {
            addCriterion("zhuan_money <>", value, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyGreaterThan(BigDecimal value) {
            addCriterion("zhuan_money >", value, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("zhuan_money >=", value, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyLessThan(BigDecimal value) {
            addCriterion("zhuan_money <", value, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("zhuan_money <=", value, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyIn(List<BigDecimal> values) {
            addCriterion("zhuan_money in", values, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyNotIn(List<BigDecimal> values) {
            addCriterion("zhuan_money not in", values, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zhuan_money between", value1, value2, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andZhuanMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zhuan_money not between", value1, value2, "zhuanMoney");
            return (Criteria) this;
        }

        public Criteria andSumZhuanIsNull() {
            addCriterion("sum_zhuan is null");
            return (Criteria) this;
        }

        public Criteria andSumZhuanIsNotNull() {
            addCriterion("sum_zhuan is not null");
            return (Criteria) this;
        }

        public Criteria andSumZhuanEqualTo(BigDecimal value) {
            addCriterion("sum_zhuan =", value, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanNotEqualTo(BigDecimal value) {
            addCriterion("sum_zhuan <>", value, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanGreaterThan(BigDecimal value) {
            addCriterion("sum_zhuan >", value, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_zhuan >=", value, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanLessThan(BigDecimal value) {
            addCriterion("sum_zhuan <", value, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_zhuan <=", value, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanIn(List<BigDecimal> values) {
            addCriterion("sum_zhuan in", values, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanNotIn(List<BigDecimal> values) {
            addCriterion("sum_zhuan not in", values, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_zhuan between", value1, value2, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andSumZhuanNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_zhuan not between", value1, value2, "sumZhuan");
            return (Criteria) this;
        }

        public Criteria andBaseReduceIsNull() {
            addCriterion("base_reduce is null");
            return (Criteria) this;
        }

        public Criteria andBaseReduceIsNotNull() {
            addCriterion("base_reduce is not null");
            return (Criteria) this;
        }

        public Criteria andBaseReduceEqualTo(BigDecimal value) {
            addCriterion("base_reduce =", value, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceNotEqualTo(BigDecimal value) {
            addCriterion("base_reduce <>", value, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceGreaterThan(BigDecimal value) {
            addCriterion("base_reduce >", value, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("base_reduce >=", value, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceLessThan(BigDecimal value) {
            addCriterion("base_reduce <", value, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("base_reduce <=", value, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceIn(List<BigDecimal> values) {
            addCriterion("base_reduce in", values, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceNotIn(List<BigDecimal> values) {
            addCriterion("base_reduce not in", values, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_reduce between", value1, value2, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andBaseReduceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_reduce not between", value1, value2, "baseReduce");
            return (Criteria) this;
        }

        public Criteria andSumBaseIsNull() {
            addCriterion("sum_base is null");
            return (Criteria) this;
        }

        public Criteria andSumBaseIsNotNull() {
            addCriterion("sum_base is not null");
            return (Criteria) this;
        }

        public Criteria andSumBaseEqualTo(BigDecimal value) {
            addCriterion("sum_base =", value, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseNotEqualTo(BigDecimal value) {
            addCriterion("sum_base <>", value, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseGreaterThan(BigDecimal value) {
            addCriterion("sum_base >", value, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_base >=", value, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseLessThan(BigDecimal value) {
            addCriterion("sum_base <", value, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_base <=", value, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseIn(List<BigDecimal> values) {
            addCriterion("sum_base in", values, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseNotIn(List<BigDecimal> values) {
            addCriterion("sum_base not in", values, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_base between", value1, value2, "sumBase");
            return (Criteria) this;
        }

        public Criteria andSumBaseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_base not between", value1, value2, "sumBase");
            return (Criteria) this;
        }

        public Criteria andYingSalaryIsNull() {
            addCriterion("ying_salary is null");
            return (Criteria) this;
        }

        public Criteria andYingSalaryIsNotNull() {
            addCriterion("ying_salary is not null");
            return (Criteria) this;
        }

        public Criteria andYingSalaryEqualTo(BigDecimal value) {
            addCriterion("ying_salary =", value, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryNotEqualTo(BigDecimal value) {
            addCriterion("ying_salary <>", value, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryGreaterThan(BigDecimal value) {
            addCriterion("ying_salary >", value, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ying_salary >=", value, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryLessThan(BigDecimal value) {
            addCriterion("ying_salary <", value, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ying_salary <=", value, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryIn(List<BigDecimal> values) {
            addCriterion("ying_salary in", values, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryNotIn(List<BigDecimal> values) {
            addCriterion("ying_salary not in", values, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ying_salary between", value1, value2, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andYingSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ying_salary not between", value1, value2, "yingSalary");
            return (Criteria) this;
        }

        public Criteria andShuiPercentIsNull() {
            addCriterion("shui_percent is null");
            return (Criteria) this;
        }

        public Criteria andShuiPercentIsNotNull() {
            addCriterion("shui_percent is not null");
            return (Criteria) this;
        }

        public Criteria andShuiPercentEqualTo(BigDecimal value) {
            addCriterion("shui_percent =", value, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentNotEqualTo(BigDecimal value) {
            addCriterion("shui_percent <>", value, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentGreaterThan(BigDecimal value) {
            addCriterion("shui_percent >", value, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shui_percent >=", value, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentLessThan(BigDecimal value) {
            addCriterion("shui_percent <", value, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shui_percent <=", value, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentIn(List<BigDecimal> values) {
            addCriterion("shui_percent in", values, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentNotIn(List<BigDecimal> values) {
            addCriterion("shui_percent not in", values, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shui_percent between", value1, value2, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andShuiPercentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shui_percent not between", value1, value2, "shuiPercent");
            return (Criteria) this;
        }

        public Criteria andSuKouIsNull() {
            addCriterion("su_kou is null");
            return (Criteria) this;
        }

        public Criteria andSuKouIsNotNull() {
            addCriterion("su_kou is not null");
            return (Criteria) this;
        }

        public Criteria andSuKouEqualTo(BigDecimal value) {
            addCriterion("su_kou =", value, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouNotEqualTo(BigDecimal value) {
            addCriterion("su_kou <>", value, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouGreaterThan(BigDecimal value) {
            addCriterion("su_kou >", value, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("su_kou >=", value, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouLessThan(BigDecimal value) {
            addCriterion("su_kou <", value, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouLessThanOrEqualTo(BigDecimal value) {
            addCriterion("su_kou <=", value, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouIn(List<BigDecimal> values) {
            addCriterion("su_kou in", values, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouNotIn(List<BigDecimal> values) {
            addCriterion("su_kou not in", values, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("su_kou between", value1, value2, "suKou");
            return (Criteria) this;
        }

        public Criteria andSuKouNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("su_kou not between", value1, value2, "suKou");
            return (Criteria) this;
        }

        public Criteria andLeiYingIsNull() {
            addCriterion("lei_ying is null");
            return (Criteria) this;
        }

        public Criteria andLeiYingIsNotNull() {
            addCriterion("lei_ying is not null");
            return (Criteria) this;
        }

        public Criteria andLeiYingEqualTo(BigDecimal value) {
            addCriterion("lei_ying =", value, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingNotEqualTo(BigDecimal value) {
            addCriterion("lei_ying <>", value, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingGreaterThan(BigDecimal value) {
            addCriterion("lei_ying >", value, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lei_ying >=", value, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingLessThan(BigDecimal value) {
            addCriterion("lei_ying <", value, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lei_ying <=", value, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingIn(List<BigDecimal> values) {
            addCriterion("lei_ying in", values, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingNotIn(List<BigDecimal> values) {
            addCriterion("lei_ying not in", values, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lei_ying between", value1, value2, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiYingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lei_ying not between", value1, value2, "leiYing");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoIsNull() {
            addCriterion("lei_jiao is null");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoIsNotNull() {
            addCriterion("lei_jiao is not null");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoEqualTo(BigDecimal value) {
            addCriterion("lei_jiao =", value, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoNotEqualTo(BigDecimal value) {
            addCriterion("lei_jiao <>", value, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoGreaterThan(BigDecimal value) {
            addCriterion("lei_jiao >", value, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lei_jiao >=", value, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoLessThan(BigDecimal value) {
            addCriterion("lei_jiao <", value, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lei_jiao <=", value, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoIn(List<BigDecimal> values) {
            addCriterion("lei_jiao in", values, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoNotIn(List<BigDecimal> values) {
            addCriterion("lei_jiao not in", values, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lei_jiao between", value1, value2, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andLeiJiaoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lei_jiao not between", value1, value2, "leiJiao");
            return (Criteria) this;
        }

        public Criteria andDangIsNull() {
            addCriterion("dang is null");
            return (Criteria) this;
        }

        public Criteria andDangIsNotNull() {
            addCriterion("dang is not null");
            return (Criteria) this;
        }

        public Criteria andDangEqualTo(BigDecimal value) {
            addCriterion("dang =", value, "dang");
            return (Criteria) this;
        }

        public Criteria andDangNotEqualTo(BigDecimal value) {
            addCriterion("dang <>", value, "dang");
            return (Criteria) this;
        }

        public Criteria andDangGreaterThan(BigDecimal value) {
            addCriterion("dang >", value, "dang");
            return (Criteria) this;
        }

        public Criteria andDangGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dang >=", value, "dang");
            return (Criteria) this;
        }

        public Criteria andDangLessThan(BigDecimal value) {
            addCriterion("dang <", value, "dang");
            return (Criteria) this;
        }

        public Criteria andDangLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dang <=", value, "dang");
            return (Criteria) this;
        }

        public Criteria andDangIn(List<BigDecimal> values) {
            addCriterion("dang in", values, "dang");
            return (Criteria) this;
        }

        public Criteria andDangNotIn(List<BigDecimal> values) {
            addCriterion("dang not in", values, "dang");
            return (Criteria) this;
        }

        public Criteria andDangBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dang between", value1, value2, "dang");
            return (Criteria) this;
        }

        public Criteria andDangNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dang not between", value1, value2, "dang");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table revenue
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table revenue
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}