spring:
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hao?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=GMT%2B8
    username: root
    password: 123456
 redis:
   host: localhost
   password:
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.mapper
#       mapper-locations: classpath:mapper/*Mapper.xml
#       type-aliases-package: com.example.demo.mapper

