package third.world.hao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import third.world.hao.model.Revenue;
import third.world.hao.model.RevenueExample;
@Mapper
public interface RevenueMapper {
    List<Revenue> selectByThree(@Param("userId") String userId,@Param("parent") String parent,@Param("month") int month);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    long countByExample(RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int deleteByExample(RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int insert(Revenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int insertSelective(Revenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    List<Revenue> selectByExample(RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    Revenue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Revenue record, @Param("example") RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Revenue record, @Param("example") RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Revenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Revenue record);

    List<Map<String,String>> selectByIdAndParent(@Param("userId")String userId);
}